ALTER TABLE t_p58147154_messenger_vcommunica.calls
  ADD COLUMN IF NOT EXISTS call_type VARCHAR(10) NOT NULL DEFAULT 'video',
  ADD COLUMN IF NOT EXISTS caller_ice_seq INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS callee_ice_seq INTEGER NOT NULL DEFAULT 0;
